refactor(api-client): Use plain TypeScript locally
wireapp/wire-web-packages pull request #3249
Opened 2020-10-08 10:06 UTC by thisisamir98

2020-10-08 10:16 UTC, bennyn approved these changes

2020-10-20 05:39 UTC, ffflorian requested changes

2020-10-20 05:39 UTC, ffflorian commented on packages/api-client/demo/demo.js
> +import {WebSocketClient} from '@wireapp/api-client/tcp/';
```suggestion
import {WebSocketClient} from '@wireapp/api-client/src/tcp/';
```

2020-10-20 13:48 UTC, ffflorian approved these changes

2020-10-20 14:35 UTC, merged