refactor(lru-cache): Use plain TypeScript locally and remove webpack & demo
wireapp/wire-web-packages pull request #3292
Opened 2020-10-22 10:51 UTC by thisisamir98

2020-10-22 10:54 UTC, ffflorian approved these changes

2020-10-22 10:58 UTC, bennyn approved these changes

2020-10-22 11:56 UTC, ffflorian requested changes
Please update the imports of `LRUCache` in the other projects.

2020-10-22 12:22 UTC, thisisamir98 commented
> Please update the imports of `LRUCache` in the other projects.

@ffflorian it's only used in cryptobox which I checked and it's fine.

2020-10-23 13:09 UTC, ffflorian approved these changes

2020-10-23 13:19 UTC, merged