feat(api-client,core): Send messages as protobuf
wireapp/wire-web-packages pull request #3356
Opened 2020-12-04 13:49 UTC by ffflorian

## Pull Request Checklist

- [x] My code is covered by tests
- [x] I will [merge the PR as breaking change](https://github.com/wireapp/wire-web-packages/wiki/Releases#create-major-release), if the API contract changes

2020-12-07 15:24 UTC, bennycode requested changes

2020-12-07 15:24 UTC, bennycode commented on packages/api-client/src/conversation/ConversationAPI.ts
> +    } else if (typeof messageData.reportMissing === 'undefined' || !messageData.reportMissing.length) {
Can this code be shared with the code used in `postBroadcastProtobufMessage`?

2020-12-21 13:38 UTC, thisisamir98 approved these changes

2021-01-04 19:23 UTC, bennycode commented
I am okay with merging this but let's declare it as **breaking change**.

2021-01-04 19:24 UTC, bennycode approved these changes

2021-01-07 09:34 UTC, merged