feat(api-client): Dedicated team size endpoint
wireapp/wire-web-packages pull request #3401
Opened 2020-12-18 09:57 UTC by Yserz

2020-12-18 16:41 UTC, lipis approved these changes

2020-12-21 09:41 UTC, ffflorian requested changes

2020-12-21 09:41 UTC, ffflorian commented on packages/api-client/src/team/team/TeamAPI.ts
>  import type {AxiosRequestConfig} from 'axios';
```suggestion
import {AxiosRequestConfig, CancelToken} from 'axios';
```

2020-12-21 09:41 UTC, ffflorian commented on packages/api-client/src/team/team/TeamAPI.ts
> +    const cancelSource = Axios.CancelToken.source();
```suggestion
    const cancelSource = CancelToken.source();
```

2020-12-21 09:41 UTC, ffflorian commented on packages/api-client/src/team/team/TeamAPI.ts
> +      url: `${TeamAPI.URL.TEAMS}/${teamId}${TeamAPI.URL.SIZE}`,
```suggestion
      url: `${TeamAPI.URL.TEAMS}/${teamId}/${TeamAPI.URL.SIZE}`,
```

2021-02-09 09:26 UTC, ffflorian approved these changes

2021-02-09 10:01 UTC, merged