refactor: move MLS code from NotificationService to MLSService
wireapp/wire-web-packages pull request #4579
Opened 2022-11-02 00:54 UTC by aweiss-dev

## Pull Request Checklist

- [ ] My code is covered by tests
- [ ] I will [merge the PR as breaking change](https://github.com/wireapp/wire-web-packages/wiki/Releases#create-major-release), if the API contract changes

2022-11-02 08:29 UTC, atomrc requested changes
Look good overall. Just a few things here and there but nice work

2022-11-02 08:29 UTC, atomrc commented on packages/core/src/mls/MLSService/MLSService.ts
> +   * ## MLS only ##
you can remove those comments 
```suggestion
```

2022-11-02 08:29 UTC, atomrc commented on packages/core/src/mls/MLSService/MLSService.ts
> +   * ## MLS only ##
```suggestion
```

2022-11-02 08:29 UTC, atomrc commented on packages/core/src/mls/MLSService/MLSService.ts
> +   * ## MLS only ##
```suggestion
```

2022-11-02 08:29 UTC, atomrc commented on packages/core/src/mls/MLSService/MLSService.ts
> +   * ## MLS only ##
```suggestion
```

2022-11-02 08:29 UTC, atomrc commented on packages/core/src/mls/MLSService/stores/pendingProposalsStore/pendingProposalsStore.ts
> +} & CommonMLS;
Can you check if it still makes sense to have this `CommonMLS`? I feel like it's only used here (in which case we can inline the `groupId` in this type

2022-11-02 08:29 UTC, atomrc commented on packages/core/src/mls/MLSService/stores/pendingProposalsStore/pendingProposalsStore.ts
> +};
Seems to be only used in tests, can probably be removed if there is not real life scenario where it's used

2022-11-02 08:50 UTC, aweiss-dev commented on packages/core/src/mls/EventHandler/ConversationEvent/ConversationEvent.ts
> +    return handleMLSMessageAdd({...params, event});
This is on purpose. Typescript doesn't recognize the right type if you try to just pass props or if props.event gets checked by the type guards.

2022-11-02 09:26 UTC, atomrc commented on packages/core/src/mls/EventHandler/ConversationEvent/ConversationEvent.ts
> +    return handleMLSMessageAdd({...params, event});
what if we do `isMLSMessageAddEvent(params.event)`, would typescript understand that `params.event` is of the right type?

2022-11-03 10:39 UTC, atomrc approved these changes

2022-11-03 13:06 UTC, merged